### ISSUE TITLE
Does rust-wasm support for MCU such as STM32-F4

### ISSUE THREAD

**Issue by lygstate** [yblein/rust-wasm#2]

**Comment by HugoGuiroux** [comment]
Hi @lygstate,

The current version of rust-wasm only interprets a wasm bytecode: it does not compile it, i.e., it does not generate assembly code from wasm code.
Thus, I guess your original question is: "Am I able to compile the rust code of rust-wasm for STM32-F4"? I let you look at [this link](https://gist.github.com/adamgreig/b47fe9159e721e368601) to compile rust code for this specific platform.
